//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleReaderDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleReaderDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _100010 {
            get {
                object obj = ResourceManager.GetObject("_100010", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _100011 {
            get {
                object obj = ResourceManager.GetObject("_100011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _100012 {
            get {
                object obj = ResourceManager.GetObject("_100012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _10005 {
            get {
                object obj = ResourceManager.GetObject("_10005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _10006 {
            get {
                object obj = ResourceManager.GetObject("_10006", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _10007 {
            get {
                object obj = ResourceManager.GetObject("_10007", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _10008 {
            get {
                object obj = ResourceManager.GetObject("_10008", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _10009 {
            get {
                object obj = ResourceManager.GetObject("_10009", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _10010 {
            get {
                object obj = ResourceManager.GetObject("_10010", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _10011 {
            get {
                object obj = ResourceManager.GetObject("_10011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _10012 {
            get {
                object obj = ResourceManager.GetObject("_10012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _10013 {
            get {
                object obj = ResourceManager.GetObject("_10013", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _10014 {
            get {
                object obj = ResourceManager.GetObject("_10014", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _10015 {
            get {
                object obj = ResourceManager.GetObject("_10015", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _10016 {
            get {
                object obj = ResourceManager.GetObject("_10016", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _10017 {
            get {
                object obj = ResourceManager.GetObject("_10017", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _10018 {
            get {
                object obj = ResourceManager.GetObject("_10018", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _10020 {
            get {
                object obj = ResourceManager.GetObject("_10020", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _10021 {
            get {
                object obj = ResourceManager.GetObject("_10021", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _10021_1 {
            get {
                object obj = ResourceManager.GetObject("_10021_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _10022 {
            get {
                object obj = ResourceManager.GetObject("_10022", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _10023 {
            get {
                object obj = ResourceManager.GetObject("_10023", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _10024 {
            get {
                object obj = ResourceManager.GetObject("10024", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _10025 {
            get {
                object obj = ResourceManager.GetObject("10025", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _10026 {
            get {
                object obj = ResourceManager.GetObject("10026", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _loading {
            get {
                object obj = ResourceManager.GetObject("_loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap _return {
            get {
                object obj = ResourceManager.GetObject("_return", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   CRC Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BaseFrame_1 {
            get {
                return ResourceManager.GetString("BaseFrame_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MID Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BaseFrame_2 {
            get {
                return ResourceManager.GetString("BaseFrame_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Control Code Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BaseFrame_3 {
            get {
                return ResourceManager.GetString("BaseFrame_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   State Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BaseFrame_4 {
            get {
                return ResourceManager.GetString("BaseFrame_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Code Queue is Full과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BaseFrame_5 {
            get {
                return ResourceManager.GetString("BaseFrame_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Incomplete Code과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BaseFrame_6 {
            get {
                return ResourceManager.GetString("BaseFrame_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overflow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string BaseFrame_7 {
            get {
                return ResourceManager.GetString("BaseFrame_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap bg {
            get {
                object obj = ResourceManager.GetObject("bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap btncheck11 {
            get {
                object obj = ResourceManager.GetObject("btncheck11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap btncheck12 {
            get {
                object obj = ResourceManager.GetObject("btncheck12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap btncheckoff1 {
            get {
                object obj = ResourceManager.GetObject("btncheckoff1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap btncheckoff11_ {
            get {
                object obj = ResourceManager.GetObject("btncheckoff11 ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap btncheckoff2 {
            get {
                object obj = ResourceManager.GetObject("btncheckoff2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap btncheckoff3 {
            get {
                object obj = ResourceManager.GetObject("btncheckoff3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap btncheckoff4 {
            get {
                object obj = ResourceManager.GetObject("btncheckoff4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap btncheckoff5 {
            get {
                object obj = ResourceManager.GetObject("btncheckoff5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap btncheckoff6 {
            get {
                object obj = ResourceManager.GetObject("btncheckoff6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap btncheckon1 {
            get {
                object obj = ResourceManager.GetObject("btncheckon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap btncheckon11_ {
            get {
                object obj = ResourceManager.GetObject("btncheckon11 ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap btncheckon2 {
            get {
                object obj = ResourceManager.GetObject("btncheckon2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap btncheckon3 {
            get {
                object obj = ResourceManager.GetObject("btncheckon3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap btncheckon4 {
            get {
                object obj = ResourceManager.GetObject("btncheckon4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap btncheckon5 {
            get {
                object obj = ResourceManager.GetObject("btncheckon5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap btncheckon6 {
            get {
                object obj = ResourceManager.GetObject("btncheckon6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Cancel {
            get {
                object obj = ResourceManager.GetObject("Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Not support this baud rate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0001_02_1 {
            get {
                return ResourceManager.GetString("Frame_0001_02_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP Parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0001_04_1 {
            get {
                return ResourceManager.GetString("Frame_0001_04_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP Parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0001_07_1 {
            get {
                return ResourceManager.GetString("Frame_0001_07_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port parameter reader hardware is not supported과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0001_09_1 {
            get {
                return ResourceManager.GetString("Frame_0001_09_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not support this Port parameter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0001_0B_1 {
            get {
                return ResourceManager.GetString("Frame_0001_0B_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter is missing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0001_0B_2 {
            get {
                return ResourceManager.GetString("Frame_0001_0B_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not support Wiegand Interface과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0001_0D_1 {
            get {
                return ResourceManager.GetString("Frame_0001_0D_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not suoport this Wiegand communication format과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0001_0D_2 {
            get {
                return ResourceManager.GetString("Frame_0001_0D_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The reader does not support the data content과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0001_0D_3 {
            get {
                return ResourceManager.GetString("Frame_0001_0D_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RTC setup failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0001_10_1 {
            get {
                return ResourceManager.GetString("Frame_0001_10_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reader MAC parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0001_13_1 {
            get {
                return ResourceManager.GetString("Frame_0001_13_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1|Hardware not supported과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0001_31_1 {
            get {
                return ResourceManager.GetString("Frame_0001_31_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0|Connect successfully과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0001_33_0 {
            get {
                return ResourceManager.GetString("Frame_0001_33_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1|Connection failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0001_33_1 {
            get {
                return ResourceManager.GetString("Frame_0001_33_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0|Closed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0001_37_0 {
            get {
                return ResourceManager.GetString("Frame_0001_37_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1|Open과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0001_37_1 {
            get {
                return ResourceManager.GetString("Frame_0001_37_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Success!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0001_48_0 {
            get {
                return ResourceManager.GetString("Frame_0001_48_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter error!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0001_48_1 {
            get {
                return ResourceManager.GetString("Frame_0001_48_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save failed!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0001_48_2 {
            get {
                return ResourceManager.GetString("Frame_0001_48_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not support this Port parameter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_01_1 {
            get {
                return ResourceManager.GetString("Frame_0010_01_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not support this Power parameter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_01_2 {
            get {
                return ResourceManager.GetString("Frame_0010_01_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not support this Frequency range parameter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_03_1 {
            get {
                return ResourceManager.GetString("Frame_0010_03_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Channel number is out of the current band range과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_05_1 {
            get {
                return ResourceManager.GetString("Frame_0010_05_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid number of frequencies과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_05_2 {
            get {
                return ResourceManager.GetString("Frame_0010_05_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_05_3 {
            get {
                return ResourceManager.GetString("Frame_0010_05_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   this antenna port does not exist과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_07_1 {
            get {
                return ResourceManager.GetString("Frame_0010_07_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_09_1 {
            get {
                return ResourceManager.GetString("Frame_0010_09_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The device does not support the baseband rate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_0B_1 {
            get {
                return ResourceManager.GetString("Frame_0010_0B_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Q value parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_0B_2 {
            get {
                return ResourceManager.GetString("Frame_0010_0B_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Session parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_0B_3 {
            get {
                return ResourceManager.GetString("Frame_0010_0B_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inventory parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_0B_4 {
            get {
                return ResourceManager.GetString("Frame_0010_0B_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_0B_5 {
            get {
                return ResourceManager.GetString("Frame_0010_0B_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mode parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_0D_1 {
            get {
                return ResourceManager.GetString("Frame_0010_0D_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_0D_2 {
            get {
                return ResourceManager.GetString("Frame_0010_0D_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Antenna port parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_10_1 {
            get {
                return ResourceManager.GetString("Frame_0010_10_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Read parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_10_2 {
            get {
                return ResourceManager.GetString("Frame_0010_10_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TID reading error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_10_3 {
            get {
                return ResourceManager.GetString("Frame_0010_10_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Userdata reading error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_10_4 {
            get {
                return ResourceManager.GetString("Frame_0010_10_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reserved Area data reading error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_10_5 {
            get {
                return ResourceManager.GetString("Frame_0010_10_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other parameter errors과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_10_6 {
            get {
                return ResourceManager.GetString("Frame_0010_10_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Antenna port parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_11_1 {
            get {
                return ResourceManager.GetString("Frame_0010_11_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tag missing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_11_10 {
            get {
                return ResourceManager.GetString("Frame_0010_11_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command sending error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_11_11 {
            get {
                return ResourceManager.GetString("Frame_0010_11_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter selection error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_11_2 {
            get {
                return ResourceManager.GetString("Frame_0010_11_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter input error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_11_3 {
            get {
                return ResourceManager.GetString("Frame_0010_11_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CRC error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_11_4 {
            get {
                return ResourceManager.GetString("Frame_0010_11_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Power shortage과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_11_5 {
            get {
                return ResourceManager.GetString("Frame_0010_11_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data Overflow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_11_6 {
            get {
                return ResourceManager.GetString("Frame_0010_11_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The data area is locked과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_11_7 {
            get {
                return ResourceManager.GetString("Frame_0010_11_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access password error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_11_8 {
            get {
                return ResourceManager.GetString("Frame_0010_11_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other tag mistakes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_11_9 {
            get {
                return ResourceManager.GetString("Frame_0010_11_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Antenna port parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_12_1 {
            get {
                return ResourceManager.GetString("Frame_0010_12_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Labels are missing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_12_10 {
            get {
                return ResourceManager.GetString("Frame_0010_12_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The reader sends a command error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_12_11 {
            get {
                return ResourceManager.GetString("Frame_0010_12_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_12_2 {
            get {
                return ResourceManager.GetString("Frame_0010_12_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lock operating parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_12_3 {
            get {
                return ResourceManager.GetString("Frame_0010_12_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CRC error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_12_4 {
            get {
                return ResourceManager.GetString("Frame_0010_12_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   underpower과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_12_5 {
            get {
                return ResourceManager.GetString("Frame_0010_12_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data Overflow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_12_6 {
            get {
                return ResourceManager.GetString("Frame_0010_12_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The data area is locked과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_12_7 {
            get {
                return ResourceManager.GetString("Frame_0010_12_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access password error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_12_8 {
            get {
                return ResourceManager.GetString("Frame_0010_12_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other tag mistakes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_12_9 {
            get {
                return ResourceManager.GetString("Frame_0010_12_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Antenna port parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_13_1 {
            get {
                return ResourceManager.GetString("Frame_0010_13_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_13_2 {
            get {
                return ResourceManager.GetString("Frame_0010_13_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CRC error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_13_3 {
            get {
                return ResourceManager.GetString("Frame_0010_13_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   underpower과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_13_4 {
            get {
                return ResourceManager.GetString("Frame_0010_13_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inactivated password error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_13_5 {
            get {
                return ResourceManager.GetString("Frame_0010_13_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other tag mistakes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_13_6 {
            get {
                return ResourceManager.GetString("Frame_0010_13_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Labels are missing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_13_7 {
            get {
                return ResourceManager.GetString("Frame_0010_13_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The reader sends a command error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_13_8 {
            get {
                return ResourceManager.GetString("Frame_0010_13_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Success과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_20_0 {
            get {
                return ResourceManager.GetString("Frame_0010_20_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Antenna port parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_20_1 {
            get {
                return ResourceManager.GetString("Frame_0010_20_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reader failed to send instructions과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_20_10 {
            get {
                return ResourceManager.GetString("Frame_0010_20_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrong parameter selection과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_20_2 {
            get {
                return ResourceManager.GetString("Frame_0010_20_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wrong parameter Untraceable과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_20_3 {
            get {
                return ResourceManager.GetString("Frame_0010_20_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CRC check error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_20_4 {
            get {
                return ResourceManager.GetString("Frame_0010_20_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Power shortage과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_20_5 {
            get {
                return ResourceManager.GetString("Frame_0010_20_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_20_6 {
            get {
                return ResourceManager.GetString("Frame_0010_20_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unsupported instructions과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_20_7 {
            get {
                return ResourceManager.GetString("Frame_0010_20_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other label errors과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_20_8 {
            get {
                return ResourceManager.GetString("Frame_0010_20_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Label loss과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_20_9 {
            get {
                return ResourceManager.GetString("Frame_0010_20_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Antenna port parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_40_1 {
            get {
                return ResourceManager.GetString("Frame_0010_40_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read the contents of parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_40_2 {
            get {
                return ResourceManager.GetString("Frame_0010_40_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter error reading the user data area과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_40_3 {
            get {
                return ResourceManager.GetString("Frame_0010_40_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Antenna port parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_41_1 {
            get {
                return ResourceManager.GetString("Frame_0010_41_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Write parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_41_2 {
            get {
                return ResourceManager.GetString("Frame_0010_41_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Antenna port parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_42_1 {
            get {
                return ResourceManager.GetString("Frame_0010_42_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Write parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_42_2 {
            get {
                return ResourceManager.GetString("Frame_0010_42_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Antenna port parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_50_1 {
            get {
                return ResourceManager.GetString("Frame_0010_50_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Read parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_50_2 {
            get {
                return ResourceManager.GetString("Frame_0010_50_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TID reading error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_50_3 {
            get {
                return ResourceManager.GetString("Frame_0010_50_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UserData Area error reading error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_50_4 {
            get {
                return ResourceManager.GetString("Frame_0010_50_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_50_5 {
            get {
                return ResourceManager.GetString("Frame_0010_50_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Antenna port parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_51_1 {
            get {
                return ResourceManager.GetString("Frame_0010_51_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Identification failure과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_51_10 {
            get {
                return ResourceManager.GetString("Frame_0010_51_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other tag mistakes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_51_11 {
            get {
                return ResourceManager.GetString("Frame_0010_51_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Labels are missing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_51_12 {
            get {
                return ResourceManager.GetString("Frame_0010_51_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command sending error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_51_13 {
            get {
                return ResourceManager.GetString("Frame_0010_51_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_51_2 {
            get {
                return ResourceManager.GetString("Frame_0010_51_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter input error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_51_3 {
            get {
                return ResourceManager.GetString("Frame_0010_51_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CRC error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_51_4 {
            get {
                return ResourceManager.GetString("Frame_0010_51_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   underpower과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_51_5 {
            get {
                return ResourceManager.GetString("Frame_0010_51_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data Overflow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_51_6 {
            get {
                return ResourceManager.GetString("Frame_0010_51_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The data area locked과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_51_7 {
            get {
                return ResourceManager.GetString("Frame_0010_51_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access password error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_51_8 {
            get {
                return ResourceManager.GetString("Frame_0010_51_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insufficient permissions과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_51_9 {
            get {
                return ResourceManager.GetString("Frame_0010_51_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Antenna port parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_52_1 {
            get {
                return ResourceManager.GetString("Frame_0010_52_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Identification failure과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_52_10 {
            get {
                return ResourceManager.GetString("Frame_0010_52_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other tag error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_52_11 {
            get {
                return ResourceManager.GetString("Frame_0010_52_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tag data missing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_52_12 {
            get {
                return ResourceManager.GetString("Frame_0010_52_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The reader sends a command error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_52_13 {
            get {
                return ResourceManager.GetString("Frame_0010_52_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_52_2 {
            get {
                return ResourceManager.GetString("Frame_0010_52_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lock operating parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_52_3 {
            get {
                return ResourceManager.GetString("Frame_0010_52_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CRC error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_52_4 {
            get {
                return ResourceManager.GetString("Frame_0010_52_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Underpower과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_52_5 {
            get {
                return ResourceManager.GetString("Frame_0010_52_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data Overflow과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_52_6 {
            get {
                return ResourceManager.GetString("Frame_0010_52_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Data area locked과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_52_7 {
            get {
                return ResourceManager.GetString("Frame_0010_52_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Access password error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_52_8 {
            get {
                return ResourceManager.GetString("Frame_0010_52_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insufficient permissions과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_52_9 {
            get {
                return ResourceManager.GetString("Frame_0010_52_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Antenna port parameter error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_53_1 {
            get {
                return ResourceManager.GetString("Frame_0010_53_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command sending error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_53_10 {
            get {
                return ResourceManager.GetString("Frame_0010_53_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter selection error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_53_2 {
            get {
                return ResourceManager.GetString("Frame_0010_53_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CRC error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_53_3 {
            get {
                return ResourceManager.GetString("Frame_0010_53_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   underpower과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_53_4 {
            get {
                return ResourceManager.GetString("Frame_0010_53_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inactivated password error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_53_5 {
            get {
                return ResourceManager.GetString("Frame_0010_53_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insufficient permissions과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_53_6 {
            get {
                return ResourceManager.GetString("Frame_0010_53_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Identification failure과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_53_7 {
            get {
                return ResourceManager.GetString("Frame_0010_53_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Other tag error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_53_8 {
            get {
                return ResourceManager.GetString("Frame_0010_53_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tag data missing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0010_53_9 {
            get {
                return ResourceManager.GetString("Frame_0010_53_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not support this Frequency parameter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0101_00_1 {
            get {
                return ResourceManager.GetString("Frame_0101_00_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not support this Port parameter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0101_00_2 {
            get {
                return ResourceManager.GetString("Frame_0101_00_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PLL lock failure과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0101_00_3 {
            get {
                return ResourceManager.GetString("Frame_0101_00_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   save parameters failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0101_01_1 {
            get {
                return ResourceManager.GetString("Frame_0101_01_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   save parameters failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0101_03_1 {
            get {
                return ResourceManager.GetString("Frame_0101_03_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   save parameters failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Frame_0101_06_1 {
            get {
                return ResourceManager.GetString("Frame_0101_06_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap waiting {
            get {
                object obj = ResourceManager.GetObject("waiting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
